### ISSUE TITLE
start-stop-daemon - ubuntu only?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/exemplar-release#3]
This is the first release I've seen I think that delegates process monitoring to start-stop-daemon. Isn't it an ubuntu/not-centos only system? Are there some other pros why this is the suggestion vs the other methods used on other releases (run the process and create pid, which monit watches)?

**Comment by wendorf** [comment]
It's unfortunately not available on CentOS, but could conceivably be packaged by a release (we haven't tested doing that, though, so it might not work).

We suggested using start-stop-daemon because it manages a lot of things for release authors that are easy to get wrong, such as locking. We also spiked on creating a custom tool ([Sipid](https://github.com/cloudfoundry/sipid)) that does this work for you and can be packaged on any non-Windows stemcell.

We should definitely think through the right recommendation for non-Ubuntu stemcells. Thanks for bringing this up.

/cc @xoebus

**Comment by xoebus** [comment]
Hmm. Most of our releases are only expected to run on Ubuntu. Since this is opt-in for releases and not a mandated BOSH change I think recommending `start-stop-daemon` is still the right thing to do for releases which only need to work on Ubuntu.

Is there an equivalent for CentOS that could be used in releases which need to support both?

**Comment by drnic** [comment]
I was initially surprised to see the delegation from one process monitoring system - monit - to another. Is this a new idea for this release or are there other bosh releases where this has been used already?

E.g. At a glance I don't see it in concourse/concourse

**Comment by xoebus** [comment]
It has been experimented with in some smaller releases to good effect.
We're looking for ways to get rid of the shame that is `pid_utils.sh`.

**Comment by gerhard** [comment]
There is a [start-stop-daemon fork written in C](https://github.com/daleobrien/start-stop-daemon) which we include in `src` & compile on both Ubuntu & CentOS like any other package. I would also like to see start-stop-daemon included in the CentOS stemcell.

Does anyone know the reason why`runit` - the supervisor used for bosh-agent & monit - is not used for release jobs? I mean, it's as close to supervision perfection as they come, and the components that it ships with are something that we've been struggling to plug with cheap knock-offs for years. Monit is stuck at 5.2.5 because AGPL, a new supervisor has been discussed for years but fails to materialise, while we end up with threads like these when runit is able to make all this redundant. Why?

**Comment by xoebus** [comment]
@cppforlife RE: the `runit` and supervisor decision.

**Comment by mkocher** [comment]
>  I mean, it's as close to supervision perfection as they come

👍 for runit.
